tatuylonen/wikitextprocessor

wikitextprocessor/lua/_sandbox_phase1.lua
wikitextprocessor/lua/_sandbox_phase2.lua
wikitextprocessor/luaexec.py

On the theme of parsing the Simple English Wiktionary, either this module must be prevented from loading or else something must be done to prevent one module from changing the global namespace for templates loaded from other pages. See the commit message for more details.

Ban poison module

---

wikitextprocessor/core.py

Some Chinese Wiktionary pages use templates for language and POS section headers([Category:语言模板](https://zh.wiktionary.org/wiki/Category:%E8%AF%AD%E8%A8%80%E6%A8%A1%E6%9D%BF), [Category:詞類模板](https://zh.wiktionary.org/wiki/Category:%E8%A9%9E%E9%A1%9E%E6%A8%A1%E6%9D%BF)). This pull request adds these templates to `Wtp.need_pre_expand`, so they can be expanded before calling `fix_subtitle_hierarchy()`at [here](https://github.com/tatuylonen/wiktextract/blob/093b6892431f1a8e796b18d17fbd8197e74ad0ba/wiktextract/page.py#L2830).

Expand Chinese Wiktionary language and POS heading templates

---

wikitextprocessor/core.py

The previous code would break normal templates, for example: `This ending is semi-{{glossary|productive}}` in https://en.wiktionary.org/wiki/-ant#German.

Remove LanguageConverter markups after all templates are expanded

---

wikitextprocessor/core.py

I forgot to add these templates in my previous commit. Some templates like ["=n="](https://linkcount.toolforge.org/?project=zh.wiktionary.org&page=Template%3A%3Dn%3D) are used in thousands of pages.

Pre-expand POS templates whose names begin with "=" in Chinese Wiktonary

---

wikitextprocessor/core.py

This pull request fixes some issues when modifying expaned text of Chinese POS heading templates so more pages could be parsed.
It also fixes the module not exists error in non-English Wiktionary Lua code.

Fix modify heading bug and fix Lua module not exists error

---

wikitextprocessor/dumpparser.py

This allows custom treatment of individual pages based on their `model`, `title`, and `text`. For example, to process only modules, one could do:
```python
def page_handler(model, title, text):
if title.startswith("Module:"):
ctx.add_page(model, title, text)
ctx = Wtp()
process_dump(ctx, dump_file, page_handler=page_handler)

allow custom page_handler arg in process_dump

---

wikitextprocessor/parser.py

Fix `archivedate` argument not included error in Module:quote(https://en.wiktionary.org/wiki/Module:quote). This error is caused by the parser treats the URL argument as external link and later converts the URL to wikitext link(`node_expand.to_html()`) in the `[url]` form with breaks the Lua code.
Module:quote checks the URL argument, if the URL starts with `https://web.archive.org/web/` then the `archivedate` argument is not required. But since the arguemnt now starts with `[https://`, it throws an error.
Example page: https://en.wiktionary.org/wiki/accent
wikitext:
```
##* {{quote-web|en|archiveurl=https://web.archive.org/web/20221219212008/https://www.newyorker.com/news/news-desk/terror-strikes-in-paris|work={{w|The New Yorker}}|passage=They were all Middle Eastern types but spoke …
```

Treate URL in template argument as plain text

---

pyproject.toml
wikitextprocessor/core.py
wikitextprocessor/dumpparser.py
wikitextprocessor/lua/_sandbox_phase2.lua
wikitextprocessor/lua/mw_wikibase.lua
wikitextprocessor/luaexec.py

`Wtp.reprocess()` filters unused pages. In order to save all extracted pages, run the save files code inside `process_dump()`. Fixes #47 
Most changes to the `core.py` are formatting code made by [black](https://github.com/psf/black).
Opening and writing millions of files are slow, it takes ten minutes to create extracted pages. I'd discourage the usage of the `--pages-dir` option, page text can be inspected by querying the database.
Also fixes these Lua errors:
- https://kaikki.org/dictionary/errors/details-module-not-found-----RQ-xum-TI----export---.html
- https://kaikki.org/dictionary/errors/details-With-part-of-speech--ger---must-specif-Q9nKZHOa.html and other `Module:it-form of` errors.
- https://kaikki.org/dictionary/errors/details-attempt-to-concatenate-local--link---a-3wtv07QZ.html …

Save extarcted pages to files

---

README.md
wikitextprocessor/core.py
wikitextprocessor/lua/_sandbox_phase2.lua

This parameter is not used since page contents are queried from database now.

Remove `autoload` parameter from `Wtp.reprocess()`

---

wikitextprocessor/lua/_sandbox_phase2.lua

The previous code converts these string keys to their correspond "infinity" and "not a number" number value, that causes the `frame_args_index()` can't find the values of these keys.
This is the correct fix for those `inf` template parameters not found Lua errors. My previous commit https://github.com/tatuylonen/wikitextprocessor/commit/0726ce7deaca522df8b48ee5680a74eb486f68d2 works but not really fixes the error.

Don't convert table key "inf" and "nan" to number

---

wikitextprocessor/parser.py

Previous commit eecb07352bc7eebc4924ed08d24b1d3fedce236a incorrectly added these two lines. This would cause the parser deletes the space between words. For example, page https://en.wiktionary.org/wiki/丫鬟 uses a `c=aa1 waan4` template parameter, but remove the whitespace would cause error in https://en.wiktionary.org/wiki/Module:yue-pron because it checks if the parameter matches "[0-9][a-z]" pattern.

Don't skip whitespace token in `parser.token_iter()`

---

wikitextprocessor/lua/mw_title.lua
wikitextprocessor/parser.py

The first commit fixes the error introduced from https://github.com/tatuylonen/wikitextprocessor/commit/eecb07352bc7eebc4924ed08d24b1d3fedce236a and pass the `test_url1` test.
The second commit fixes https://kaikki.org/dictionary/errors/details-attempt-to-index-a-nil-value-----links-rfq-IHVw.html

Fix previous URL parser commit and a Lua error

---

tests/test_wikiprocess.py
wikitextprocessor/core.py
wikitextprocessor/dumpparser.py

Also only run `Wtp.analyzed_templates()` if it's the first time parsing a dump file or template pages are overwritten or the results of `analyzed_templates()` are not saved to db last time.

Don't commit changes to db if some pages are temporally overwritten

---

wikitextprocessor/core.py
wikitextprocessor/lua/_sandbox_phase1.lua
wikitextprocessor/luaexec.py

According to Scribunto
document(https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#mw.loadData), `mw.loadData()` evalutates the loaded module only once per page, rather than once per `{{#invoke:}}` call. The cache should be cleared for each page, otherwise some module like
`Module:headword/data`(https://en.wiktionary.org/wiki/Module:headword/data) would use old cached page title.

Clear `mw.loadData()` cache before processing each page

---

.github/workflows/test.yml

This would run tests when commits are pushed to a branch or pull request. And it won't interfere with existing test workflow. The test results can be viewed from my forked repository: https://github.com/xxyzz/wikitextprocessor/actions/runs/5195143853

Add test GitHub Actions

---

wikitextprocessor/lua/mw_title.lua
wikitextprocessor/luaexec.py

This function is used in Lua code to check if a page exists. It calls `Wtp.get_page()` and `get_page()` uses namespace id to process the title. If namesapce id is not passed it may not find the page.
For example, https://zh.wiktionary.org/wiki/Module:Zh-dial-syn loads Lua module like this `local resource_page = "Module:zh/data/dial-syn/" .. target_page`, `get_page()` needs the namesapce id to change the title to `Module:Zh/data/dial-syn/*`.

Pass namespace id to `get_page_info()`

---

wikitextprocessor/core.py

`if body` is also `False` if variable `body` is an empty string, thus the variable `t` will remain `None` and later the `assert isinstance(t, str)` code will fail. Actually, `body` can't be `None`, because the template name is check with `Wtp.template_exists()` before.
Example template: https://zh.wiktionary.org/wiki/Template:中2 this template's body is empty string after proccessing with `Wtp.__template_to_body()`.

Check template body is not `None` explicitly in `Wtp.expand.expand_recurse()`

---

tests/test_parser.py
wikitextprocessor/parser.py

Template arguments can be written in multiple lines. And the "\n" at the end of the template name is parsed as the first unamed argument and later got trimed to empty string. This causes first argument missing error in page "father", wikitext:
```
#* {{quote-web
|en
|date=August 01, 1980
|origdate=1 May 1980
...
}}
```
Fixes https://github.com/tatuylonen/wiktextract/issues/275

Strip new lines from template arguments

---

tests/test_wikiprocess.py
wikitextprocessor/core.py
wikitextprocessor/lua/mw_title.lua

previous Lua code only adds the array index number but not the value to the `prefixes` table.
Checking page namespace at here probably is not needed, since only main and reconstruction namespaces are queried in the second phase.

Fix `mw.title.getCurrentTitle` returns `nil` Lua error for page "1:e"

---

tests/test_wikiprocess.py
wikitextprocessor/core.py

`Wtp._analyze_template()`'s local variable for called template name overwrites the analyzed template name, which would cause the following check Chinese Wiktionary heading template code uses the called template name.

Fix template name variable got overwritten by called template name bug

---

tests/test_long.py
tests/test_node_expand.py
tests/test_parser.py
tests/test_wikiprocess.py
wikitextprocessor/core.py
wikitextprocessor/parser.py

`test_invoke8` and `test_invoke13` are removed because they are duplicate of `test_invoke7` and `test_invoke12`.
The temporary SQLite files will be deleted even when the tests fail.

Add unittest.TestCase.tearDown() to delete temporary db files

---

wikitextprocessor/lua/_sandbox_phase2.lua

These two functions are created in `language.setupInterface`(https://github.com/wikimedia/mediawiki-extensions-Scribunto/blob/4aa17cb80c72998b9cead27e5be1ca39d8a0cfed/includes/Engines/LuaCommon/lualib/mw.language.lua#L27-L28) and the recent change to page `Module:languages` used them to replace `mw.ustring.upper` and `mw.ustring.lower`(https://en.wiktionary.org/w/index.php?title=Module:languages&diff=prev&oldid=75145580).

Assign `string.uupper` and `string.ulower` Lua function to fix Lua error in Module:languages

---

.github/workflows/test.yml
Makefile
pyproject.toml
tests/testcov.conf
tools/get_namespaces.py

GitHub Pages need to be enabled at page https://github.com/tatuylonen/wikitextprocessor/settings/pages, the build source needs to be set to "GitHub Actions".
A preview of the coverage pages: https://xxyzz.github.io/wikitextprocessor

Upload code coverage HTML files to GitHub Pages

---

wikitextprocessor/core.py

Example: https://zh.wiktionary.org/wiki/Template:土家語

Some Chinese Wiktionary templates use the simplified varient of template name "語言標題"

---

tests/test_parser.py
wikitextprocessor/core.py
wikitextprocessor/node_expand.py
wikitextprocessor/parser.py

WikiNode previously had one attribute that held two kinds of argument data: either a single string, for things like HTML tag names, List "##*"-style level strings etc., or a list of lists containing more complicated data, like Template arguments and stuff.
It's really hard to keep track of, and a really annoying thing to write well-typed code for. Because by necessity you'd need to have it be a [str | List[List[...]]], you have to constantly create phantom asserts either with `# type: ignore` or `if TYPE_CHECKING: assert...` to make type-checkers happy.
`sarg` and `largs` are both preliminary names: string argument and list arguments, specifically, but if someone can come up with something better, these two should be unique enough to be easily replaceable.

Separate WikiNode.args into WikiNode.sarg and WikiNode.largs

---

tests/test_wikiprocess.py
wikitextprocessor/core.py

SQL query in `Wtp.get_page` returns page "Template:Cite-book" first and this page redirects to "Template:cite-book" again thus causes the infinite recusion.

Fix infinite recursion caused by "Template:cite-book"

---

wikitextprocessor/lua/mw_html.lua

https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#mw.html:cssText Scribunto document and code
https://github.com/wikimedia/mediawiki-extensions-Scribunto/blob/c588e717ab150ecfe951e4356d7c6331bf264f18/includes/Engines/LuaCommon/lualib/mw.html.lua#L376-L384 say the "mw.html:cssText" function: "If a nil parameter is passed, this is a no-op.", so it should not return `nil`.

Fix `index nil` Lua error in English Wiktionary "Module:Message box"

---

wikitextprocessor/lua/mw.lua
wikitextprocessor/lua/mw_language.lua
wikitextprocessor/lua/mw_message.lua
wikitextprocessor/parserfns.py

All three commits are simple implementations to fix errors in the English Wikipedia page "Free neutron decay".
The [message](https://www.mediawiki.org/wiki/Help:System_message) library is for getting localized strings. I just return the massage key, we could implement it in the future if it's needed for expanding templates. And the message data are stored in JSON files: https://github.com/wikimedia/mediawiki/tree/master/languages/i18n

Add mw.message Lua library

---

tests/test_parser.py
wikitextprocessor/parser.py

Previous code uses a for loop to iterate each argument list thus ignores the empty unnamed parameter and makes the second unnamed parameter to the first one incorrectly.

Set empty unnamed template parameter to empty string

---

tests/test_parser.py
wikitextprocessor/core.py
wikitextprocessor/parser.py

`LevelNode.find_content()` could be used by French Wiktionary extractor to find the subtitle template inside the level node.

Add new `WikiNode` subclass `LevelNode`

---

tests/test_parser.py
tests/test_wikiprocess.py
wikitextprocessor/core.py
wikitextprocessor/parser.py

Unnamed template parameter might also use named parameters format if the value contains "=".

Change template parameter name to int value if it's a number

---

wikitextprocessor/lua/mw_site.lua

Fixes Lua errors in some Arabic pages from French Wiktioanry. Example page: https://fr.wiktionary.org/wiki/ف ت ح
The error happends in https://fr.wiktionary.org/wiki/Module:arabe, line 1313: `mw.title.makeTitle( "template",racine):getContent()`. This Lua module uses the lower case canonical name, but our Lua code `mw_site.matchNamespaceName()` can't find it because the `canonicalName` is localized name("Modèle").

Pass namespace canonical name to Lua class `Namespace`

---

pyproject.toml

Currently, the code is not compatible with python 3.8, since 3.9 features are frequently used. This commit drops support for python 3.8 and requires python 3.9 via pyproject.toml.

drop support for python 3.8 and require 3.9

---

pyproject.toml
wikitextprocessor/core.py
wikitextprocessor/luaexec.py

The use of importlib.resources.files is not supported in python_version<3.10. This commit uses the backport package importlib-resources instead.
Picked from #107.

use backport package importlib-resources for python_version<3.10

---

README.md

Having the -e flag before the --use-pep517 flag causes the error:
ERROR: --use-pep517 is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

Fix order of flags in install instructions for test environment

---

wikitextprocessor/lua/mw_title.lua

MediaWiki code doesn't have these checks, I only removed 3 lines to fix Lua errors in French Wiktionary.

Remove some title checking rules in `mw_title.makeTitle()`

---

.github/workflows/test.yml
wikitextprocessor/core.py
wikitextprocessor/parserfns.py

- Add tests for Python 3.9 and 3.12
- Don't hide Deprecation warnings in tests
- Fix a regex bug in https://github.com/tatuylonen/wikitextprocessor/commit/6feffe33c84b92e145f4a304bf1080014e62ed4a
- Replace some date format code with `datetime.strftime()`
- Replace deprecated `datetime.utcnow()`

Fix some Python warnings

---

src/wikitextprocessor/core.py

This error was found by GitHub Code Scan, here is the screenshot from my forked repo:
<details>
<summary>screenshot</summary>
</details>

Fix regex characters range "A-Z"

---

.github/dependabot.yml
.github/workflows/lint.yml

[Dependabot](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot)  creates pull-requests automatically that keeps GitHub Actions dependencies up-to-date. It can be enabled in the project's settings page's "Code security and analysis" section.

Add GitHub dependabot config file

---

src/wikitextprocessor/core.py
src/wikitextprocessor/dumpparser.py
tests/test_wikiprocess.py

Pre-expand templates is not very useful for the French Wiktionary. For example, translation start template "trad-début" doesn't need to be expanded and it's sense parameter would be lost if expanded. And it also moves the translation list nodes inside some HTML tags.

Add an option to skip analyzing templates

---

src/wikitextprocessor/core.py
tests/test_parser.py

Previous template regex pattern can't match templates with parameter that has a "{" right after "}". Also remove the table pattern to keep the pattern simple, tables are never used in template parameters.
Resolves https://github.com/tatuylonen/wiktextract/issues/365.
Pray this change won't break anything...

Match latex math formula in template parameters

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Add ":" to the HTML tag regex pattern and fix a regex flag error in the `inside_html_tags_re` variable.

Allow matching HTML tags that have XML attribute

---

src/wikitextprocessor/core.py

This bug was found in https://github.com/tatuylonen/wiktextract/issues/389, but this pr only fixes two cases. `Wtp._analyze_template()` sill has more backtracking bugs while processing the Russian Wikipedia templates. The code now stuck at page https://ru.wikipedia.org/wiki/Шаблон:Результаты_зимних_Олимпийских_игр_2006, this template seems to use the `{{!}}` template at the end of the table.

Fix two catastrophic backtracking cases when matching wikitext table

---

src/wikitextprocessor/data/es/namespaces.json
tools/get_namespaces.py

I started to look at the Spanish Wiktionary and noted that the namespaces are not named correctly. Especially the Appendix namespace which seems to hold the best source of language data.
I have added a format commit so that at least the diff of the last commit allows to see which namespace data has changed.

Update Spanish namespace data

---

src/wikitextprocessor/core.py

This extra `?` causes catastrophic backtracking in page https://en.wiktionary.org/wiki/Template:sw-conj/table
But the regex still has more backtrack bugs if it can't match a table, we're just lucky the templates are not long enough to halt the command. Many templates are marked need pre-expand is because the table can't be matched.
We should use a simpler approach to count and compare the numbers of `{|` and `|}`.

Revert `?` added to the analyze template table regex pattern

---

README.md
pyproject.toml
src/wikitextprocessor/core.py
src/wikitextprocessor/luaexec.py
tests/test_lua.py

`mw.language.fetchLanguageName` and `mw.language.fetchLanguageNames` use the language data extracted from CLDR(https://cldr.unicode.org)
I can't find the ICU API to get language code from language name, but I guess we could use `getAvailable()` to build a dictionary. Then we could use the icu package to replace the language JSON files in the wiktextract package.
pyicu's doc says the `libicu-dev` package is required on Debian: https://gitlab.pyicu.org/main/pyicu#installing-pyicu

Get language names from ICU

---

src/wikitextprocessor/luaexec.py
tests/test_node_expand.py

Fixes Lua errors in English Wiktionary page "oxymoronicness" and "Gendergap".
Lua error message: `[string "Module:languages/error"]:87: The language or  etymology language code "re" is not valid (see [⁠[⁠Wiktionary:List of languages]]): title=re:publica 2014, der 1.`
It seems "Module:quote" splits the argument by ":" and checks if it is language code at line 209.

Don't process Template args with `html.unescape()`

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py
tests/test_parser.py

In my quest for adding basic support for parsing further Wiktionary editions, I have started to look into the Russian Wiktionary and ran immediately into a problem.
As per their conventions, a the [page structure](https://ru.wiktionary.org/wiki/Викисловарь:Правила_оформления_статей) of a Russian Wiktionary entry uses h1 headings to start the different language sections.
For example:
```
= {{-en-}} =
== yield I ==
=== Морфологические и синтаксические свойства ===
{{сущ en||||}}
{{морфо|прист1=|корень1=|суфф1=|оконч=|частица=}}
=== Произношение ===
{{transcriptions||}}
=== Семантические свойства ===
```
This pull request is to add support for parsing level 1 headings to WikiNodes with kind == NodeKind.LEVEL1, necessary for correctly extracting the Russian Wiktionary.
---
Comments:
- My …

Add NodeKind.LEVEL1 to parser to support parsing the Russian Wiktionary

---

src/wikitextprocessor/common.py
src/wikitextprocessor/core.py
src/wikitextprocessor/parserfns.py
tests/test_wikiprocess.py

https://meta.wikimedia.org/wiki/Help:Newlines_and_spaces#Automatic_newline
Before certain key character, "*", ";", ":", "{|", "#", wikitext expansion (afaict both templates and parserfns) should have an inserted newline '\n' at the start of the string.
This doesn't directly fix the original issue where this was detected, but this small commit should at least shift the code to be more correct.
There may be kludges still left in other parts of the code that emulate this behavior for specific contexts, but those probably rely on heuristically detecting when something is wrong, so they shouldn't by mistriggered easily by this change.
If some code is found that inserts newlines or splits lines before the characters mentioned above, it might be ok to remove that kludge.

Add newlines before key chars when expanding

---

src/wikitextprocessor/core.py

The original table regex has serious backtracking bug in some pages and it marks 140 false positive templates as having unpaired table.
Before the change the code runs several minutes for the English Wiktionary dump file and hung for the Russian Wikipedia dump file. It now finishes instantly.
Here are the templates marked as having unpaired tables before but not after this change:
<details>
<summary>click to expand</summary>
<code>
[
"Template:roa-lor-conj-être",
"Template:no-verb table passive",
"Template:wa-conj-er-R",
"Template:roa-fcm-conj-étre",
"Template:klj-infl-noun/sandbox",
"Template:liv-noun-pū/forms",
"Template:frp-old-conj-aveir",
"Template:mt-conj",
"Template:sa-conj-pre-58",
"Template:rgn-conj-first-cons-table",
"Template:roa-gal-conj-anduirr", …

Remove catastrophic backtracking table regex in `_analyze_template`

---

src/wikitextprocessor/lua/_sandbox_phase1.lua
src/wikitextprocessor/lua/_sandbox_phase2.lua

I got a strange Lua timeout error from the 20231201 Chinese Wiktionary dump file on page "还了得", a simple page. The Lua error is at the `_lua_reset_env()`, before running the Lua module code.

Clear the timeout hook after a Lua model is finished execution

---

src/wikitextprocessor/interwiki.py
src/wikitextprocessor/parserfns.py
tests/test_wikiprocess.py

Fix Lua error in page "https://en.wiktionary.org/wiki/bánh_tây"

Resolve interwiki prefix in `fullurl` parser function

---

src/wikitextprocessor/lua/_sandbox_phase1.lua

An unreproducible Lua error on kaikki.org in page "बुझ्नु": `lupa.lua51.LuaError: [string "<python>"]:80: bad argument 1 to 'setfenv' (number expected, got nil)`
But the Lua function error message is not in the log.

Return Lua `loadstring()` error message

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Due to an oversight (because it didn't happen on
en.wiktionary.org), italics or bold inside a header broke the header token detection, because
headers were detected as part of a tokenizing regex that was run on a partitioned line if there were any italics or bold tokens present.
To fix this, just detect headers before-hand; even previously, headers were handled by recursively
tokenizing their contents, so this was pretty much just copy-pasting stuff around, thankfully.
Test written originally by @empiriker
Co-authored-by: empiriker

Detect header tokens before italics/bold

---

src/wikitextprocessor/core.py
tests/test_parser.py

I'm not sure what error that commit was trying to fix, the current code has no problem process the translation section of the "quadratic" page and the "trans-top" template's body is `{{#invoke:translations|top}}`. Even if a template parameter is passed to `#invoke` and it contains `=` the code is still correct and don't need to replace `=`.
Remove this code fixes the Lua error in page "can" because `=` is replaced to `&#61;` and causes a error in module "translations/multi".

Remove code added from commit 6d2d466b2a640961c68cb93db6330f40cdf8a588

---

.github/dependabot.yml
.github/workflows/lint.yml
.github/workflows/test.yml

"typos" doesn't have a stable tag("v1") like other actions and it updates quite frequently. Also update some action dependencies.

Ignore patch updates of the "typos" command

---

src/wikitextprocessor/parserfns.py
tests/test_parser.py

Used in page "Star Trek" and "Coriandrum sativum" but not required for extracted JSON file.

Implement `PAGELANGUAGE` and `#language` magic words

---

.github/dependabot.yml
.github/workflows/lint.yml
src/wikitextprocessor/dumpparser.py
src/wikitextprocessor/interwiki.py
src/wikitextprocessor/parserfns.py
tests/test_lua.py

Call the `siteinfo` MediaWiki API only once and share the data across worker processes.

Save interwiki maps data to SQLite db file

---

pyproject.toml
src/wikitextprocessor/common.py
src/wikitextprocessor/core.py
src/wikitextprocessor/dumpparser.py
src/wikitextprocessor/luaexec.py
src/wikitextprocessor/node_expand.py
src/wikitextprocessor/parser.py
src/wikitextprocessor/parserfns.py
src/wikitextprocessor/wikihtml.py

Updating the syntax to Python 3.9 type hinting, also attempted to take care of a few 3.9-specific issues (like function signatures that have been changed since 3.9, but still have a 3.9-friendly 'form' that can be used).

Type checking 3.9

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parserfns.py
tests/test_wikiprocess.py

`Wtp.namespaces` is only used in `ns_fn`, create another dictionary to save namespace data seems unnecessary.

Clean up `ns` parser function code

---

src/wikitextprocessor/core.py

Chinese extractor uses `frozenset` and failed at these lines. I enabled optimizations and `assert` are removed in this mode so I didn't find the error before. This is a bit annoying. All pages failed...

Allow frozenset type passed to `Wtp.expand()` and `Wtp.parse()`

---

src/wikitextprocessor/parser.py

It's convenient to have this value to search level nodes or check if a node is level node.

Add a flag variable of level node kinds

---

src/wikitextprocessor/core.py
src/wikitextprocessor/luaexec.py
tests/test_parser.py
tests/test_wikiprocess.py

Any page can be used as template:
https://www.mediawiki.org/wiki/Help:Templates#Usage
This feature is used in French Wiktionary's Conjugaison page.

Transclude any page as template

---

src/wikitextprocessor/core.py

Many Lua modules call [Module:debug/track](https://en.wiktionary.org/wiki/Module:debug/track) to try to expand some tracking templates like [Template:tracking/affix](https://en.wiktionary.org/wiki/Template:tracking/affix), so the error is expected and templates are expanded correctly.

Remove "can't find template" error

---

src/wikitextprocessor/core.py
tests/test_parser.py

Find this in French Wiktionary's Conjugaison page.
Hopefully this won't break anything...

Allow apostrophe in template parameter name

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Can't expand nodes at here, and this error happens on a misuse of link as template name. Not sure if there are real usage of template for a template name, probably not very common.

Fix 'WikiNode' object has no attribute 'strip' error

---

src/wikitextprocessor/core.py
tests/test_parser.py

The previous regex pattern matches `<nowiki />` as a start tag therefore includes the second "if" argument into the first argument.

Don't match HTML end tag as start tag in arguments

---

src/wikitextprocessor/parser.py
tests/test_node_expand.py
tests/test_parser.py

Previously, tokens such as `{|`, `|+`, `|-` and `|}` were allowed to function as tokens for parsing tables even when they weren't at the beginning of a line, or following whitespace at the beginning of a line. This is incorrect.
`|` and `!` (separating headers and cells) when singular need to be at the start of the line or after start of line whitespace, but not `||` and `!!` which are used within a line. `|` is a bit more complicated because the `|` token is also used an attribute separator in tables!
Had to change a few mistaken tables. `{| |}` results in broken tables because the `|}` is not parsed without a newline, and our parser will consume the rest of the section or document. Wikimedia's parser does something weird, and in this case the empty table above (without a proper end …

Accept whitespace before certain table tokens

---

src/wikitextprocessor/core.py
tests/test_wikiprocess.py

[Module:debug/track](https://en.wiktionary.org/wiki/Module:debug/track) expands tracking templates through the Lua frame "expandTemplate" method. The previous code doesn't remove the template name from `Wtp.expand_stack` when template doesn't exist and causes the stack grow too much longer.
The previous code shouldn't skip this line: https://github.com/tatuylonen/wikitextprocessor/blob/8dc20c04ab68fc9c28bcaf751490a14b0fd0fbc8/src/wikitextprocessor/core.py#L1563
Error code: https://github.com/tatuylonen/wikitextprocessor/blob/8dc20c04ab68fc9c28bcaf751490a14b0fd0fbc8/src/wikitextprocessor/core.py#L1365-L1369 
Errors on kaikki.org: https://kaikki.org/dictionary/errors/details-too-deep-recursion-during-template-expansion.html

Fix template expansion recursion too deep error

---

src/wikitextprocessor/data/ru/namespaces.json
src/wikitextprocessor/luaexec.py

Fix the Lua module page not found error by replacing namspace prefix.

Fix Lua module not found error in Russian Wiktionary

---

src/wikitextprocessor/core.py
src/wikitextprocessor/dumpparser.py
src/wikitextprocessor/lua/_sandbox_phase1.lua
src/wikitextprocessor/lua/_sandbox_phase2.lua
src/wikitextprocessor/luaexec.py
tests/test_wikiprocess.py

Error page: https://ru.wiktionary.org/wiki/русский

Fix expand `{{t:=}}` wikitext bug from Russian Wiktionary

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py
tests/test_parser.py
tests/test_wikiprocess.py

`Wtp.namespace_prefixes` is copied from
`wiktextract.datautils.ns_title_prefix_tuple`.
There are two wiktextract test errors use the
`TemplateNode.template_name` property and the name string is sliced incorrectly from my last commit.

Fix two wiktextract test errors caused by 02ae183

---

src/wikitextprocessor/core.py
tests/test_node_expand.py

"Template arguments" (triple-brace constructions like {{{foo}}}, {{{foo|bar}}} and {{{|bar}}}) were previously rendered as text when they were found outside of a template call (ie. they weren't an 'argument').
Wiktionary sandbox will render
```
{{{foo|bar}}}
{{{foo}}}
{{{|baz}}}
{{{foo|{{{bar|baz}}}}}}
```
as `bar {{{foo}}} baz baz`, because even though "foo" is an empty variable, the defaults should still render, and the empty variable on its own should decompose into a string. Previously, all of the above would fallback to decomposing as a string ( {{{foo|bar}}} -> '{{{foo|bar}}}').

Fix: {{{foo|bar}}} should return 'bar' outside template call

---

pyproject.toml
src/wikitextprocessor/luaexec.py

By default, only language codes defined in MediaWiki's php code are returned from `mw.languages.fetchLanguageNames`(when the `include` argument is not passed).
Previous code of `get_all_names` returns all languages, [v0.2.0](https://github.com/xxyzz/mediawiki_langcodes/releases/tag/v0.2.0) adds the second bool argument to control whether returns MediaWiki defined languages or all languages.
Issue #201

Pass `include` argument to `mediawiki_langcodes.get_all_names()`

---

src/wikitextprocessor/core.py
tests/test_parser.py

Fixes issue tatuylonen/wiktextract#499
Previous regex matches `{{m|mul|{ }}` but not `{{m|mul{}}`.

Allow `{` before another curly bracket inside template

---

Makefile
src/wikitextprocessor/core.py
src/wikitextprocessor/luaexec.py
tests/test_wikiprocess.py

Should fix #208
This stripping is done at the point of calling because removing the newline when in _encode, for example, removes some data we might want to keep for when we use node_to_wikitext and revert the parse tree back to text. Then the newlines would be gone.
Co-authored by: xxyzz

Strip newlines from end template arguments when calling

---

src/wikitextprocessor/luaexec.py
tests/test_wikiprocess.py

`args[0]["args"]` is a full Lua table, which is not necessarily all string values. This caused at least some Lua errors when html.escape assumed `v` was a string; `v.replace()` would panic.

Fix bug in _sandbox_phase2/make_frame/extensionTag

---

src/wikitextprocessor/core.py
src/wikitextprocessor/lua/mw_html.lua
src/wikitextprocessor/parserfns.py
src/wikitextprocessor/wikihtml.py
tests/test_wikiprocess.py

Fix this bug:
```lua
local htmlTitle = mw.html.create('span')
:attr{ id = 'coordinates' }
:addClass( displayinline and 'noprint' or nil )
:wikitext( "" )
```
Our implementation would break after :addClass because it would return nil, when it should have returned `self`, so that :wikitext() would not try to 'index' a nil value. Even if the mw.html method doesn't succeed, it should return `self` for this chaining; I checked the scribunto source, and none of the methods returned without returning something or `self`.

Chaining methods in mw.html should probably return self

---

src/wikitextprocessor/core.py
src/wikitextprocessor/node_expand.py
src/wikitextprocessor/parser.py
src/wikitextprocessor/parserfns.py
tests/test_parser.py
tests/test_parserfns.py

Because we want to allow parsing HTML-like extension tags, like `<maplink>` data, we need to add them to the HTML tag data we have, but changing ALLOWED_HTML_TAGS and messing around with capitalised globals doesn't seem the way to go.
ALLOWED_HTML_TAGS will stay as the base on which everything is built, but what should be generally used in the future instead is Wtp.allowed_html_tags, which should also include HTMLTagData entries for extra tags.
Because a bunch of other globals rely on ALLOWED_HTML_TAGS, these also need to be brough back inside the context object, generated in Wtp.__init__().
There was one place with ALLOWED_HTML_TAGS left outside of the context, in `to_wikitext` where a parse tree is turned back into text; here, it was used only to check if a lone tag (`<tag>` without an …

Move HTML tag data to Wtp context instead of global

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Fix parse exception page de edition page "axitiosus", and use `raise Exception` so the `token` variable value could be included in the error message.
Error page: https://kaikki.org/dewiktionary/errors/details-----EXCEPTION-while-parsing-page--axit-Ob46aw13.html

Allow slash in HTML attribute value

---

src/wikitextprocessor/core.py
tests/test_parser.py

Partial fix to #225
We can't get 100% correspondence with how Wikimedia parses things because our parser works on different principles, but here's a fix for an edge case. I found a few other edge-cases (added commented-out tests for them) that I don't think we can fix.
The regexes for the parsing-loop in core.py where we turn links, external links, template arguments and templates into magical characters to be stored out of the way while doing inside-out parsing are now outside the function def itself in global space.
The link regex has been changed to accept (in some cases) stray square brackets inside the link itself (but not double brackets or paired brackets).
The link regex also can now contain curly braces, etc. because we handle checking whether the link contains templates etc. in …

Changes to parser regex

---

src/wikitextprocessor/parserfns.py
src/wikitextprocessor/wikidata.py
tests/test_parser.py
tests/test_parserfns.py

Currently, #statements return some raw data without processing happening, which is what we would want
.#property to be, although #property also changes the data.
For example, coordinates are formatted, and should not be in the form 'Point(2.294479 48.858296)'.
We might need to implement all of these if we want to be 'correct'...
This commit just takes the code from #statements, puts it in .#property where it fits 'better' and then has #statements called property_fn; same output of 'raw' data, which is hopefully good enough for most purposes.

Implement partial #property parserfn

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parserfns.py
tests/test_parserfns.py

Rarely used, but still needed for things not to break.
Implemented with a simple Sqlite query to get length of page body. #pagesize should return bytesize, not number of characters (depends on encoding), so to be correct we cast body as a blob which now returns bytesize.
The Sqlite version on our machines is old enough
(a couple of years) that it doesn't implement
octet_length(), which would do this without any casting.
XXX: refactor the "name conversion + ->  namespace_id" code in get_page into its own function; this implementation of `#pagesize` returns the size of the first hit `WHERE title = ?`, so it could *TECHNICALLY* return the wrong length, but I'm not sure if this ever really ends up mattering; this is an edge case among edgecases, and almost always we just want PAGESIZE to …

Implement rudimentary #pagesize parserfn

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parserfns.py
tests/test_parserfns.py

Because we don't have access to the files (and shouldn't rely on them) and the search-function that returns a file url based on just the file name, this is implemented with a dummy URL that just starts with "//unimplemented/".
The double slash is a "protocol relative" url that seems to be the default (only?) form of url returned by #filepath, based on testing in the sandbox.
The original function has three return value variations:
- empty string when something goes wrong
- url
- PHP array [ $url, "nowiki" => true] -> Lua table -> Python dict {1: url, "nowiki": True}??
The last one is a mystery, but using the `nowiki` parameter doesn't seem to affect the return string at all. I'm not sure what it is supposed to be do, and why this happens when an array is returned. It's possible that the …

Implement #filepath / filepath parser function

---

src/wikitextprocessor/lua/mw.lua
src/wikitextprocessor/lua/mw_ext.lua
tests/test_lua.py

mw.ext is a general namespace for Mediawiki
Lua extensions, and mw.ext.data is for
https://github.com/wikimedia/mediawiki-extensions-JsonConfig/
The extension is used to retrieve JSON data from
.tab files in (typically?) Commons space. The function returns a table with data containing:
`{ schema = { fields: { ... },
data = { ... },
license = "CC0-1.0"
}`
and some optional fields.
It also should be able to return a `{ false }` table as a negative result, but the problem we're trying to fix (French Wikipedia module using mw.ext.data.get) doesn't handle that gracefully, because it already 'knows' what data it should be getting.
The code we're targetting with this fix accesses both data.schema.fields and data.data with ipairs(), so we need to go that deep and put empty tables there to be …

Implement dummy mw.ext.data.get function

---

src/wikitextprocessor/__init__.py
src/wikitextprocessor/common.py
src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py

Turns out https://github.com/tatuylonen/wikitextprocessor/commit/c25029df514c7e34820782476e6d297150081eaf makes the code slow(the `Wtp.preprocess_text()` function)... but `Wtp.process_text` is also called before `Wtp._encode()` in `Wtp.expand()`. This pr remedies a bit, after apply this pr the code is still twice slow as the code before c25029df514c7e34820782476e6d297150081eaf but faster than master.

Some regex pattern object changes

---

src/wikitextprocessor/parserfns.py

Originally by LeMoussel
Co-authored by: LeMoussel
No tests because mocking datetime.now seems impossible for now.
A better implementation might be to give Wtp
it's own static time object that can be used instead of actual time, so that it can be set to whatever is needed.
A simpler implementation is to just always give out the same exact time, maybe the start of the epoch.

Implement some LOCAL[TIME] parserfns

---

src/wikitextprocessor/luaexec.py
tests/test_wikiprocess.py

Our implementation of mw.text.decode was broken due to a misreading of
https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#mw.text.decode
Here it is said that
> If boolean decodeNamedEntities is omitted or false,
> the only named entities recognized are `&lt;` (<),
> `&gt;` (>), `&amp;` (&), `&quot;` (") and `&nbsp;`
> (the non-breaking space, U+00A0).
> Otherwise, the list of HTML5 named entities to
> recognize is loaded from PHP's get_html_translation_table function.
Tatu read this as "if decodeNamedEntities is omitted or false, decode only these values", but it turns out that `decodeNamedEntities` is only required to decode *name entities* that aren't in this list; all number values are still decoded. I have no idea why this is like this, and I had the same …

Fix: mistaken implementation of mw.text.decode

---

src/wikitextprocessor/parserfns.py

Implement 
- `{{LOCALMONTHNAME}}` “Local” name of current month
- `{{LOCALMONTHABBREV}}`  “Local” common abbreviation of the current month

Implement localmonthname & localmonthabbrev parserfns

---

src/wikitextprocessor/luaexec.py
tests/test_lua.py

Upper case `X` before HTML entity number is not supported in Scribunto, so we could only use the lower case `x`.

Fix HTML regex pattern and add a test for `mw.text.decode()`

---

src/wikitextprocessor/core.py
tests/test_parser.py

`m.start(1)` returns the location in the text passed to `re.sub()` not the location in the matched group text.
Fix https://github.com/tatuylonen/wiktextract/issues/533

Fix misuse of `Match.start()` causes template expanded as text bug

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Fixes tatuylonen/wiktextract#535
It works for now, but we'll have more errors with this regex in the future, only using a real HTML parser could fix them.

Determine a HTML tag is self-closing if it ends with "/>"

---

src/wikitextprocessor/core.py

Some wikiprojects have translated syntax for
`[[File` / `[[Image` image/file display links, like French wikipedia `Fichier`.
In Wiktextract clean_value, links with `File` and
`Image` are basically returned as empty strings, so we'll continue doing that for now; might change things for `class=noviewer` which inlines an image, and which might require handling of alt texts.

Add `file_aliases` parameter to Wtp

---

Makefile
src/wikitextprocessor/common.py

`//` is a wiki-internal URL prefix that means 'take the url prefix (https:// or http:// usually) and replace this `//` with it'. But we don't handle URLs in-between like this, it doesn't make any sense for us to do so without a website that a user is accessing, so for now let's just allow `//` links as valid links.
Parallel change on the Wiktextract side of things in clean_values, where we start to use URL_STARTS to check for valid URLs, too.

Add `//` to allowed URL prefixes

---

pyproject.toml

lupa 2.1 is released, we finally don't have to build lupa from source.

Install lupa package's wheel file

---

src/wikitextprocessor/lua/mw.wikibase.entity.lua
src/wikitextprocessor/lua/mw_wikibase.lua
src/wikitextprocessor/luaexec.py
src/wikitextprocessor/wikidata.py
tests/test_lua.py

Cache entity data JSON string to SQLite file.
Hard code the language code and site id as "en" and "enwiki", should use values in the `Wtp` object, not sure how to setup the object like the MediaWiki code(`Entity.setupInterface`).
`mw.wikibase.entity:formatPropertyValues` and
`mw.wikibase.entity:formatStatements` are not implemented, they use php code to format values.
Some methods of the entity object call not implemented functions of the `mw.wikibase` table, errors are expected.

Implement `mw.wikibase.getEntity` Lua API

---

src/wikitextprocessor/luaexec.py
src/wikitextprocessor/parserfns.py
tests/test_lua.py
tests/test_parserfns.py

Error message: https://kaikki.org/dewiktionary/errors/details--AttributeError--object-has-no-attribu--jaFhCzt.html
It's really difficult to fix bugs like this without stack trace of the "pcall" Lua function...

Fix 'AttributeError' object has no attribute 'gsub' error in de edition

---

src/wikitextprocessor/core.py
tests/test_parser.py

Should fix #266
The previous version did not allow for links with newlines in the text portion of the link:
```
[[this link|
should be
accepted]]
```
Newlines are not allowed in the link data portion ('this link').
Because of the negative lookahead stuff to detect `[[`, `]]` and `[`, `]` pairs inside the links, it's a real monster of a regex that's hard to read.
I also found a minor bug that meant a part of the regex was basically disabled, so I just removed it (no ^ to negate \n in [\n]).
Also added a negative lookbehind: a link starting with `[[[` is parsed as text.

Change to link detection regex

---

src/wikitextprocessor/parserfns.py
tests/test_wikiprocess.py

Quotation mark should be used, both `#lst`'s document and real use case(ru edition page "поверхностный") has the marks.
But I don't know when the `#lst` function in that ru page is expanded.

Match quoted `begin` `end` attribute of the `section` tag for `#lst`

---

src/wikitextprocessor/core.py

On the wiki side, an empty link is ultimately
rendered as something like `[[#Language]]`, as
text and not a link; I am pretty sure this is not
behavior that anything actually relies on, so
we can just render it as text by returning
escape brackets and the 'contents' (whitespace,
maybe) in repl_link.

Return empty links ("[[ ]]") as escaped text

---

src/wikitextprocessor/parserfns.py

- DEBUG logging level is only set to our own `Logger` obejct in wiktextract code and won't affect other packages: tatuylonen/wiktextract#591
- I guess the warning filter was added for the "dateparser" package, this was fixed two years ago(dateparser GH issue 1013)

Remove unnecessary warning and logging setting code

---

src/wikitextprocessor/lua/_sandbox_phase1.lua
tests/test_lua.py

As the Scribunto code and the GH issues(#90, #258) shows, `mw.loadData()` runs in a cloned environment so the caller env doesn't affect the code runs inside `loadData`.
I finally sort of understand this clone env problem...

Run `mw.loadData()` in cloned environment

---

src/wikitextprocessor/core.py

If a link is in the form `[[Something#other|]]` it is rendered as text and is broken and we will just ignore it.
Links that are not broken:
`[[Something|]]` without # in the first arg
`[[#Other||]]` with another pipe; everything after the first pipe is part of the second argument
for link text. It is rendered as "|"...

Link parsing: more broken link logic

---

src/wikitextprocessor/core.py
src/wikitextprocessor/dumpparser.py
src/wikitextprocessor/logging_utils.py

Our previous code use the root logger configed in wiktextract code, but now wiktextract doesn't use root logger thus all info level logs are not printed.

Create `Logger` object and set `Logging.DEBUG` level

---

src/wikitextprocessor/lua/mw_uri.lua

Still don't know how MediaWiki implements `anchorEncode`, I found this function could unescape "&#x2A;" in Wiktionary's Lua debug console.
This change fixes the "The specified language Proto-Turkic is unattested, while the given word is not marked with '*' to indicate that it is reconstructed." Lua errors in "Reconstruction" pages
MediaWiki code:
https://github.com/wikimedia/mediawiki-extensions-Scribunto/blob/755b549fe66628a2891e9a61a9abade238dd0e9b/includes/Engines/LuaCommon/UriLibrary.php#L29-L33 https://github.com/wikimedia/mediawiki/blob/6592072169f1c25d43723e0956c701855aa4c6ab/includes/parser/CoreParserFunctions.php#L1058-L1062
Lua error: https://kaikki.org/dictionary/All%20languages%20combined/errors/details-The-specified-language-Proto-Turkic-is-yS4Aqcfj.html#LUA-error-in--invoke-- …

Unescape "&#x2A;" to "*" in `mw.uri.anchorEncode()`

---

src/wikitextprocessor/core.py

0 and above 1000 are allowed in MediaWiki, for example, fr edition's "cardinaux/vi" template:
https://fr.wiktionary.org/wiki/Modèle:cardinaux/vi

Remove the limit of unnamed template argument number

---

src/wikitextprocessor/core.py
tests/test_node_expand.py

It's not uncommon in non-en editions to have `{{{x||}}}` in templates.

Don't add too many template args debug message for empty args

---

src/wikitextprocessor/core.py

`[test]]` is not a valid link, so prevent that with negative lookahead. This caused problems in cases like:
{{quote-book|en|author=[[w:Theodore Beza|Theodore de Beza]]
|tlr=[[w:Robert Fills|R[obert] F[ills&#93;]]......
with the open `[` bracket messing with the last `]]` token, causing the later LINKS_RE pattern call to basically take ages.

Change external links `[...]` regex

---

src/wikitextprocessor/core.py

an upper case "SAFESUBST:" is used in https://en.wiktionary.org/wiki/Template:ordinal
Issue https://github.com/tatuylonen/wiktextract/issues/663

Remove upper case substitution modifiers

---

src/wikitextprocessor/dumpparser.py

New dump files start from 20240601 use version 0.11: https://gerrit.wikimedia.org/r/c/operations/mediawiki-config/+/1038392
Please note with this change older dump files will not be extracted. I have checked en, zh and de editions and all these dump files don't have empty pages.

Update XML dump file namespace version

---

src/wikitextprocessor/parserfns.py
tests/test_parserfns.py

Used in ru edition's "Шаблон:родств-блок" template. Doesn't affect extracted text but remove many unimplemented error messages.
I only consider the common use cases, MediaWiki's code are complex and we don't need to handle all the edge cases at the moment.

Implement `#rel2abs` parser function

---

src/wikitextprocessor/wikidata.py

This is a `database is locked` in the ru edition log from page "হৃদয়": `LUA error in #invoke('Wdl-bn', 'all', 'L301993') parent None`
Use context manager to automatically commit should fix this racing bug.

Use connection context manager in `get_entity_data()`

---

src/wikitextprocessor/parser.py
tests/test_parser.py

https://en.wikipedia.org/wiki/Help:Wikitext#Horizontal_rule
GitHub issue tatuylonen/wiktextract#536

Only parse `----` as horizontal rule if it's at the start of line

---

src/wikitextprocessor/lua/mw_title.lua

Align with Scribunto, fix nil Lua error at en module "template link" line 43.
Example page: Nihilarian

Set empty string as Lua title object `fragment` field default value

---

src/wikitextprocessor/core.py
tests/test_parser.py

Template could contain `<nowiki/>` tag and needs to be converted, otherwise the `<span>` tag is parsed as text but not `HTMLNode`.
Find the bug in pl edition "etym" template.

Call `Wtp.preprocess_text()` again after calling `Wtp.expand()` in `Wtp.parse()`

---

src/wikitextprocessor/node_expand.py
tests/test_node_expand.py

wiktextract code `clean_node()` calls `Wtp.node_to_html()` and finally to `to_wikitext()`.
This function converts `{{PAGENAME}}` to `{{PAGENAME:}}`, and the second form expands to empty string but not page title.
Find this error when fixing ja edition exceptions.
All wiktextract tests passed.

Don't add empty argument to parser functions in `to_wikitext()`

---

src/wikitextprocessor/lua/_sandbox_phase1.lua
src/wikitextprocessor/lua/_sandbox_phase2.lua
src/wikitextprocessor/lua/mw.lua
src/wikitextprocessor/luaexec.py
tests/test_lua.py

Used in https://pl.wiktionary.org/wiki/Moduł:transliterator
The `tostring(mod)` change is for fixing `attempt to concatenate lcoal 'mod' (a userdata value)` Lua error at that line.

Implement `mw.loadJsonData()`

---

src/wikitextprocessor/core.py
tests/test_parser.py

Put `<nowiki/>` at any other place expands to normal external url link.

Only parse external link as text if `<nowiki/>` directly after `[`

---

src/wikitextprocessor/parserfns.py

It is used in ja edition template:
https://ja.wiktionary.org/wiki/テンプレート:en-noun

Support upper case `#default` branch in `#switch` parser function

---

src/wikitextprocessor/node_expand.py
src/wikitextprocessor/parser.py
tests/test_parser.py

When parsing lists, Wtp.node_to_wikitext will not reverse the transformation correctly:
```
#: example 1
#: example 2
```
becomes:
```
#:#: example 1
#: example 2
```
This seems like the result of a really old kludge that seems unnecessary now. I think WikiNode has changed between now-and-then, and the prefix of the line might have been explicitly added to only later so the old code wasn't update and there was an extra kludge inserting "#"+":" when two lists were next to each other (as in when you have a line starting with "#" followed by ":", for example; same depth, different lists).

Node to wikitext

---

src/wikitextprocessor/parserfns.py
tests/test_parserfns.py

This is required in ru edition's language title template "--lang--" to create language category link.

Return empty string for `{{ns:0}}` and `{{ns:}}`

---

src/wikitextprocessor/parser.py
tests/test_parser.py

it shouldn't pop nodes in parser stack if it's inside an unclosed node like a template
fixes #310

Don't let section start token break unclosed parent node

---

src/wikitextprocessor/node_expand.py
src/wikitextprocessor/parser.py
tests/test_parser.py

Fix zh edition exception: https://kaikki.org/zhwiktionary/errors/details-----EXCEPTION-while-parsing-page-----i-YTyJLi-P.html

Only parse section node if the token is at the beginning of a line 

---

src/wikitextprocessor/parserfns.py
tests/test_parser.py
tests/test_parserfns.py

It's used in Dutch Wiktionary's "ISOdate" Lua module, return language code for `{{int:lang}}` in a Wiktionary project.

Implement "int" parser function

---

src/wikitextprocessor/wikihtml.py
tests/test_parser.py

Dutch Wiktionary's example template expands this kind of HTML tags, previous code move the "div" tag outside the "ref" tag and break the "ref" tag, make it unclosed.
I don't really know what's the difference between "flow" and "phrasing", but this works.

Allow "div" tag inside "ref" tag

---

.github/workflows/lint.yml
.github/workflows/test.yml
pyproject.toml

3.13 tests take more time because the lupa package doesn't have 3.13 wheel file and needs to be built.

Add Python 3.13 to test action

---

src/wikitextprocessor/parser.py

When given a literal NodeKind.LEVEL*, `.find_child` returns a LevelNode.

Overload WikiNode.find_child with a LEVEL variant

---

src/wikitextprocessor/parser.py

To make find_html work the same was as find_child, allow `target_tag` (now `target_tags`) to be a list of strings instead of a single string, and return
all HTML element children with one of those tags.

find_html: allow list of tags to find.

---

src/wikitextprocessor/lua/mw_wikibase.lua
src/wikitextprocessor/luaexec.py
src/wikitextprocessor/wikidata.py
tests/test_lua.py

Fix Lua error in ko edition "bor" template, Lua module "languages", page "병신".
Add `print` in Lua pages to find error is really nerve-racking...

Implement `mw.wikibase.getSitelink()`

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Error message: `AttributeError: 'str' object has no attribute 'append'` https://kaikki.org/nlwiktionary/errors/details-----EXCEPTION-while-parsing-page--aanb-R-~wgGCv.html
"7={{template}}" parameter doesn't increase `unnamed_parameter_index` variable, should use the changed `int` type `parameter_name` variable to add its value.

Fix `AttributeError` in nl edition page "aanbalken"

---

src/wikitextprocessor/core.py
tests/test_wikiprocess.py

also find this false positive bug in en edition's [quote-song](https://en.wiktionary.org/wiki/Template:quote-song) template, it has some nested "ifmatch" templates.

Don't treat nested template in template parameters as expansion loop

---

src/wikitextprocessor/luaexec.py
tests/test_lua.py
tests/test_wikiprocess.py

Fix Lua error in [Template:R:gem:HGE](https://en.wiktionary.org/wiki/Template:R:gem:HGE), Lua's math library doesn't have `sum` function, should load "Module:math".

Load Lua module namesapce page not standard library for `#invoke`

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Fixes second part of #336
When we would normally be pushing a layer of NodeKind.PREFORMATTED, check if the stack has any HTML-elements with the `<ref>` tag and if that is the case don't push PREFORMATTED.
If other HTML-like tags need this in the future (onlyinclude? includeonly??) then this is the place where to add those checks.
Looking through the stack could be better. Filter? Any? Oh yeah, duh.

`<ref>` should ignore whitespace preformatted lines

---

src/wikitextprocessor/core.py
tests/test_parser.py

but keep white spaces
fix tatuylonen/wiktextract#912

Remove new line characters directly after wikitext comment

---

src/wikitextprocessor/core.py

Remove single newline *before* HTML comment, not after

---

src/wikitextprocessor/dumpparser.py

old code doesn't save template "!" if analyze template is not enabled and it breaks pt edition's table templates.

Save default templates

---

src/wikitextprocessor/core.py
tests/test_wikiprocess.py

Minor changes for it edition's section title templates, shouldn't affect en code.

Expand template changes for Italian Wiktionary

---

src/wikitextprocessor/parser.py
tests/test_parser.py

Wikimedia parses heading tokens from inside out:
== Foo = is parsed as  =, "= Foo ", =, with leftover `=` characters in-between the bookends ending up in the the heading itself. Fixes issue #352.
Fixed by in the portion of the code where we tokenize headings. Happily, this is already done with a regex matching a whole line, so modifying the contents of the match is easy.
I will now fix and make tests. Fails one test because the output is different from expected (mismatched `=` now go inside the heading instead of being children of the level).

Heading tokens `==` should be parsed from outside in.

---

src/wikitextprocessor/lua/mw_uri.lua
tests/test_lua.py

similar to #276, but this time "makeDisplayText()" converts "*" to "&# 42;"

Fix Lua error in reconstruction pages

---

src/wikitextprocessor/core.py
src/wikitextprocessor/data/de/namespaces.json
src/wikitextprocessor/data/el/namespaces.json
src/wikitextprocessor/data/en/namespaces.json
src/wikitextprocessor/data/es/namespaces.json
src/wikitextprocessor/data/fr/namespaces.json
src/wikitextprocessor/data/it/namespaces.json
src/wikitextprocessor/data/ja/namespaces.json
src/wikitextprocessor/data/ko/namespaces.json
src/wikitextprocessor/data/ku/namespaces.json
src/wikitextprocessor/data/nl/namespaces.json
src/wikitextprocessor/data/pl/namespaces.json
src/wikitextprocessor/data/pt/namespaces.json
src/wikitextprocessor/data/ru/namespaces.json
src/wikitextprocessor/data/simple/namespaces.json
src/wikitextprocessor/data/th/namespaces.json
src/wikitextprocessor/data/zh/namespaces.json
src/wikitextprocessor/lua/mw_site.lua
src/wikitextprocessor/lua/mw_title.lua
tests/test_wikiprocess.py
tools/get_namespaces.py

Wiktextract issue https://github.com/tatuylonen/wiktextract/issues/1009
Pagename data passed into templates or modules was split on slashes, so you'd get output like `Bing`
and `Bed` instead of `A/Bing` and `A/Bed`.
We had some copied code from Scribunto handling
slashes in titles, but it didn't do a check for
whether slashes should be considered 'subpages',
like Module:mainmodule/submodule. `Main:` which
is our main concern, doesn't have subpages and
slashes should be considered part of the title.
I've only done a quick and dirty fix here, because we only concern ourselves with Main:, Template:
and Module:; All other should hopefully have
subpages (default assumption except for Main:)
or not have slashes in their titles.

Do not split pagenames with slashes in `Main:`

---

src/wikitextprocessor/core.py

Maybe this code could be moved to wiktextract package's `clean_node()`?

[ku] remove LanguageConverter markups for ku edition

---

src/wikitextprocessor/core.py
src/wikitextprocessor/lua/_sandbox_phase2.lua
src/wikitextprocessor/lua/mw.lua
src/wikitextprocessor/luaexec.py
src/wikitextprocessor/parser.py
tests/test_lua.py

https://el.wiktionary.org/w/index.php?title=%CE%A0%CF%81%CF%8C%CF%84%CF%85%CF%80%CE%BF:%CE%B5%CF%84
```
-->|0={{{0|}}} |00={{{00|}}} {{#if:{{{nocat|}}}|{{{nocat|}}}}}|000={{{000|}}} {{#if:{{{nodisplay|}}}|{{{nodisplay|}}}}}<!--
```
Apparently parameter names under 1, like '0' or '00' aren't changed to integers... Or that Scribunto handles all parameter names as strings and just does something special with the indexing stuff.
Still need to figure out some things...

Greek wiktionary uses '0', '00' and '000' as parameters

---

src/wikitextprocessor/core.py

Most non-en editions only check template names. "Template:-vi-" in id edition redirect to a language section template.

Don't skip redirect pages in `Wtp.analyze_templates()`

---

src/wikitextprocessor/parserfns.py
tests/test_wikiprocess.py

Fixes #369
Turns out that if you have a switch statement like
`{{#switch:|a=one|#default|b=three|c=two}}`
the default option will be "three". Previously, we assumed that `#default` would only appear with an assignment, like `#default=foo`, but it can be part of a chain.

Fixed bug with `#switch` parser function `#default`

---

pyproject.toml

- `project.license` as a TOML table is deprecated
- License classifiers are deprecated
These warnings are displayed when using `python -m build` but not `python -m pip install .`

Fix two `SetuptoolsDeprecationWarning`

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py
tests/test_parser.py
tests/test_wikiprocess.py

In Spanish Wiktionary, "plural" is a template

Don't parse template as parser function

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py
tests/test_parser.py
tests/test_wikiprocess.py

zh edition has a "Template:PAGENAME" page, but `{{PAGENAME}}` is actually a magic word, only `{{PAGENAME|aaa}}` is template.
Following fix for #375

Fix template loop in Chinese Wiktionary

---

src/wikitextprocessor/parser.py
tests/test_parser.py

the section start and end token should be in the same line, fix #377

Use line number to find the matching section node

---

pyproject.toml

1.2.2 has a broken pickle cache fails "test_time34".

Downgrade dateparser 1.2.1

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py
tests/test_parser.py

fix Lua error in cs edition, "|" in external links should be parsed as plain text

Allow pipe character in external links
