tatuylonen/wikitextprocessor

wikitextprocessor/core.py

Fix tatuylonen/wikitextprocessor#1

---

wikitextprocessor/luaexec.py

Lua code in MediaWiki Module usually uses "Module:module_name" but the module page title uses the local namespace name. Chinese Wiktionary use the same English name thus the code didn't run into the error mentioned in issue #20 before. Resolve #20.

Use local Module namespace name if the module page is not found

---

wikitextprocessor/core.py

This fixes a failing test in wiktextract test suite on Windows. With this all unittests pass on Windows for wiktextract.

Update core.py to support Windows

---

tests/test_wikiprocess.py
wikitextprocessor/lua/mw_title.lua

previous code's regex can't match the substring after the last slash in title, copy code from Scribunto in order to fix tatuylonen/wiktextract#268

Copy create subpage title attibute code from Scribunto

---

wikitextprocessor/parser.py

If the list token is "#:", then the code pops stack until the stack
top is the second list in the stack.
This fixes the nested list in English Wiktionary page "a"'s "Norwegian
Bokmål" section:
```
#* {{quote-lite|nb|year=1999|author={{w|Lars Roar Langslet}}|title=I kamp for norsk kultur|page=234|passage=bruken av a i bestemt form i hunkjønnsord|t=the use of a in the definite form of feminine words}}
#: {{ux-lite|nb|[[fra A til B]]|[[from A to B]]|inline=1}}
#: {{ux-lite|nb|[[fra A til Å]]|[[from A to Z]]|inline=1}}
```
I can't add this WikiText to git commit message, it's as if git or my text editor sanitizes the code.
Template "quote-lite" expands to HTML tags but some tags are unclosed,
and it has two newlines at the end which pop the stack too early for
the following example lists. …

pop parser stack to the correct list node

---

tests/test_node_expand.py

I forgot to add this test in my previous pull request.

Add expanding template that has empty body test

---

tests/test_parser.py
wikitextprocessor/common.py
wikitextprocessor/core.py
wikitextprocessor/parser.py

Update template matching regex in `Wtp._encode()`

---

tests/test_wikiprocess.py
wikitextprocessor/core.py

Please see the 758998cefb5e2be9507f84108ef903c709413d9a commit message and test case.

Set need_pre_expand if a template is redirected from a pre expand template

---

pyproject.toml
tests/test_parser.py
wikitextprocessor/core.py
wikitextprocessor/parser.py

The parse is broken for the two HTML tests...

Add `TemplateNode` and `HTMLNode` subclasses

---

tests/test_wikiprocess.py
wikitextprocessor/core.py

Resolves https://github.com/tatuylonen/wiktextract/issues/319 and a better fix for https://github.com/tatuylonen/wikitextprocessor/pull/92.

Only query the upper case title if the original title is not found

---

wikitextprocessor/parser.py

Usage examples can be found in test files and https://github.com/tatuylonen/wiktextract/pull/320

Add some comments to `WikiNode` and `TemplateNode` methods

---

tests/test_parser.py
wikitextprocessor/parser.py

Only if the parameter has a single value the parameter is not a list.

TemplateNode class's template_parameters dictionary should use list value

---

src/wikitextprocessor/parser.py
tests/test_parser.py

to support selecting multiple node types

Change `NodeKind` to `enum.Flags`

---

src/wikitextprocessor/luaexec.py

Scribunto does this: https://www.mediawiki.org/wiki/Extension:Scribunto#Lua_environment

Clear Lua environment for each `{{#invoke:}}`

---

src/wikitextprocessor/core.py
src/wikitextprocessor/lua/_sandbox_phase1.lua
src/wikitextprocessor/lua/_sandbox_phase2.lua
src/wikitextprocessor/lua/mw.lua
src/wikitextprocessor/lua/mw_title.lua
src/wikitextprocessor/luaexec.py
tests/test_lua.py

- revert #142
- clone Lua env for each `#invoke`

Clone Lua env for each `#invoke`

---

src/wikitextprocessor/core.py
tests/test_parser.py

numbered parameter could be placed anywhere

Don't increase the index number of anonymous template arguments after numbered parameter

---

README.md
src/wikitextprocessor/core.py
src/wikitextprocessor/interwiki.py
src/wikitextprocessor/lua/mw_site.lua
src/wikitextprocessor/luaexec.py
tests/test_lua.py

Fix Lua errors in "Reconstruction:Proto-Indo-European/*" pages.

Implement `mw.site.interwikiMap()`

---

src/wikitextprocessor/parserfns.py
src/wikitextprocessor/wikidata.py
tests/test_parser.py

I should expand the arguments.

Fix `#statements` error

---

src/wikitextprocessor/wikidata.py

Fix the `UNIQUE constraint failed` SQL error.

Use `insert or ignore` in `save_item_cache()`

---

src/wikitextprocessor/core.py
tests/test_parser.py

Only parse link as plain text if nowiki tag is direct child

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py
tests/test_wikiprocess.py

I forgot to change the "Template" string, `get_page` processes any namespace pages.

Replace hard coded namespace name in `Wtp.get_page()`

---

src/wikitextprocessor/core.py
src/wikitextprocessor/parser.py

Going through wiktextract is turning up a ton of
stuff that I missed or got wrong with wikitextprocessor.

Missed type check stuff that I'm filling in

---

src/wikitextprocessor/parserfns.py
tests/test_parserfns.py

Add support of MediaWiki timestamp format to #time parser function

---

src/wikitextprocessor/lua/mw_wikibase.lua
src/wikitextprocessor/luaexec.py
src/wikitextprocessor/wikidata.py
tests/test_lua.py

and `mw.wikibase.getEntityIdForCurrentPage`, issue #216

Implement `mw.wikibase.getEntityIdForTitle`

---

src/wikitextprocessor/core.py
src/wikitextprocessor/luaexec.py
src/wikitextprocessor/parserfns.py

I wonder if all these "or"s are costly...

Appeasing the type-checker

---

src/wikitextprocessor/core.py
tests/test_parser.py
tests/test_wikiprocess.py

Process <nowiki> tags in the template body before expanding template

---

src/wikitextprocessor/lua/mw_uri.lua

Resolve Issue https://github.com/tatuylonen/wikitextprocessor/issues/237

Remove LUA Print

---

src/wikitextprocessor/parserfns.py

Implement
- `{{LOCALDOW}}` “Local” rank of current weekday (0–6)

Implement localdow parserfns 

---

src/wikitextprocessor/parserfns.py

Implements 
- `{{CURRENTDAYNAME}}` 	Name of the current day of the week
- `{{CURRENTTIME}}` 		Current hour and minutes
- `{{CURRENTHOUR}}`         Current time
- `{{LOCALDAYNAME}}` 		“Local” Name of the current day of the week
- `{{LOCALTIME}}` 		“Local” Current hour and minutes
- `{{LOCALHOUR}}` 		“Local” Current time

Implements Day Name, Time and Hour

---

src/wikitextprocessor/luaexec.py

Restore HTML named entity regex pattern

---

src/wikitextprocessor/parserfns.py

"NUMBEROFARTICLES" is used in page
https://de.wiktionary.org/wiki/entry

Implement "NUMBEROFPAGES" and "NUMBEROFARTICLES" magic words

---

src/wikitextprocessor/dumpparser.py

Resolves https://github.com/tatuylonen/wiktextract/issues/371, but slower than `lbzcat`.

Use bz2 Python library if `lbzcat` and `bzcat` are not installed

---

src/wikitextprocessor/data/el/namespaces.json

Created by `tools/get_namespaces.py`, manually change the "Appendix" namespace key.

Update el edition namespace data

---

src/wikitextprocessor/data/simple/namespaces.json

created with "tools/get_namespaces.py"

Update simple English Wiktionary namespace file

---

src/wikitextprocessor/data/ko/namespaces.json
src/wikitextprocessor/data/nl/namespaces.json

Files are created with tools/get_namespaces.py

Update Korean and Dutch Wiktionary namespace JSON files

---

src/wikitextprocessor/core.py
tests/test_wikiprocess.py

Fix tatuylonen/wiktextract#894
`test_template16` is removed because it's not a valid test, it has infinite loop.
I can't reproduce the loop in test, but it has the same repeated expand stack as the error message. The test stops at "too deep recursion" error without the change but it fixes the loop in page "今生".

Detect template loop formed in Lua code

---

src/wikitextprocessor/core.py
tests/test_parser.py

Only remove one newline character after wikitext comment

---

src/wikitextprocessor/data/it/namespaces.json
src/wikitextprocessor/data/pt/namespaces.json

created by "tools/get_namespaces.py" with some manual translations

Update pt and it edition namespace files

---

src/wikitextprocessor/wikidata.py

Find one error in en edition log, likely a rare racing bug.

Fix potential sqlite "UNIQUE constraint failed" error

---

src/wikitextprocessor/lua/mw_ext.lua
src/wikitextprocessor/lua/mw_title.lua
src/wikitextprocessor/parserfns.py

Fix Lua errors in en edition page "Reriûasu" an "gûará".

Implement `mw.ext.ParserFunctions.expr` Lua API

---

src/wikitextprocessor/data/th/namespaces.json

created with tools/get_namespaces.py and some manual translations

Update Thai Wiktionary namespace file

---

.github/dependabot.yml
.github/workflows/lint.yml

Use typos action's major version

---

.github/workflows/test.yml
src/wikitextprocessor/parser.py

Small improvement for #378

---

src/wikitextprocessor/parser.py
tests/test_parser.py

en page "bump" in issue tatuylonen/wiktextract#1196

Don't close list node if new line is inside HTML tag

---

src/wikitextprocessor/wikidata.py

language code is not always two letters, #380

Fix potential bug in `query_entity_id_for_title()`

---

src/wikitextprocessor/parser.py
tests/test_parser.py

only strip leading and trailing white spaces, fix tatuylonen/wiktextract#1218

Keep space inside named template parameter

---

src/wikitextprocessor/parserfns.py
tests/test_parserfns.py

This is used in vi edition template "like-entry"

Replace parameters in system message
